### ISSUE TITLE
Dump DK5 database and parse it into elasticsearch

### ISSUE THREAD

**Issue by hyatt03** [DBCDK/tanterne#2]
**Tasks**
- [x] Dump DK5 basen
- [x] Konverter til Elastic Search load format
- [x] Load Elastic Search
